development:
  adapter: postgresql
  database: namerator_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: namerator_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: namerator
  pool: 5
  timeout: 5000
