# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89573b4f511855f1b1d26d46063dd08bef0bfcf1ea29356401c583a8b7510346cc879812287fa4676de2e6d7f4191db7810b556708b0b99f2188d296f3c3e44c

test:
  secret_key_base: f4a678855112d7cc855a316d1156fa03e6df7321cf68537717b129048ea17a01247a97e2a70b54fc53a921cc78f87995a0139d70380a36d519372ade450ae76e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
